# Generated by Django 3.2.25 on 2024-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='departure_time',
            field=models.DateTimeField(default=None),
        ),
    ]
