# Generated by Django 3.2.25 on 2024-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_train_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
