# Generated by Django 3.2.25 on 2024-05-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_train_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='departure_time',
        ),
    ]
